import { spawnSync, spawn } from "node:child_process";
import { resolve } from "node:path";
import { existsSync, copyFileSync, writeFileSync } from "node:fs";

const REPO_ROOT = resolve(import.meta.dirname, "../..");
const DEV_VARS = resolve(REPO_ROOT, ".dev.vars");
const DEV_VARS_E2E = resolve(REPO_ROOT, ".dev.vars.e2e");
const DEV_VARS_BACKUP = resolve(REPO_ROOT, ".dev.vars.e2e-backup");
const MOCK_PID_FILE = resolve(REPO_ROOT, ".e2e-mock.pid");

// Safe defaults for a fresh checkout. `.dev.vars.e2e` is gitignored
// because it can also hold a developer's private experiments, but the
// suite only needs mock-auth + mock Google Places to run. If the file
// is missing we materialize it here so `pnpm test:e2e` works against
// a plain `git clone`.
const DEV_VARS_E2E_DEFAULT = `# Auto-generated by tests/e2e/global-setup.ts when missing.
# Safe to edit locally; it is excluded from git via .gitignore.
MOCK_AUTH=true
GITHUB_CLIENT_SECRET=e2e-unused-mock-auth-is-on
SESSION_SECRET=e2e-session-secret-not-for-production
GOOGLE_MAPS_API_KEY=e2e-mock-key
GOOGLE_PLACES_BASE_URL=http://localhost:5181
`;
// Isolate E2E state from local dev state. Must match the path passed to
// the cloudflare() plugin in vite.config.ts when LAUNCH_E2E=1.
const E2E_PERSIST = ".wrangler-e2e/state";
const E2E_ENV = { ...process.env, WRANGLER_PERSIST_TO: E2E_PERSIST };

function run(cmd: string, args: string[]): void {
	const result = spawnSync(cmd, args, {
		stdio: "inherit",
		cwd: REPO_ROOT,
		env: E2E_ENV,
	});
	if (result.status !== 0) {
		throw new Error(`Command failed: ${cmd} ${args.join(" ")}`);
	}
}

function wranglerExec(sql: string): void {
	run("pnpm", [
		"wrangler",
		"d1",
		"execute",
		"launch-db",
		"--local",
		"--persist-to",
		E2E_PERSIST,
		"--command",
		sql,
	]);
}

export default async function globalSetup() {
	// Swap .dev.vars so wrangler dev starts with test-mode bindings.
	if (!existsSync(DEV_VARS_E2E)) {
		console.log("[e2e] .dev.vars.e2e missing — seeding with mock defaults");
		writeFileSync(DEV_VARS_E2E, DEV_VARS_E2E_DEFAULT);
	}
	if (existsSync(DEV_VARS) && !existsSync(DEV_VARS_BACKUP)) {
		copyFileSync(DEV_VARS, DEV_VARS_BACKUP);
	}
	copyFileSync(DEV_VARS_E2E, DEV_VARS);
	console.log("[e2e] .dev.vars swapped with .dev.vars.e2e");

	// Launch detached mock Google Places server. Teardown kills it via PID.
	const mock = spawn(
		"node",
		["tests/e2e/mocks/start-mock.mjs"],
		{
			cwd: REPO_ROOT,
			detached: true,
			stdio: "ignore",
			env: { ...process.env, MOCK_PLACES_PORT: "5181" },
		},
	);
	if (!mock.pid) throw new Error("failed to spawn mock server");
	writeFileSync(MOCK_PID_FILE, String(mock.pid));
	mock.unref();

	// Wait for the mock to be reachable before letting wrangler dev start up.
	const deadline = Date.now() + 10_000;
	while (Date.now() < deadline) {
		try {
			const r = await fetch("http://localhost:5181/places/X/photos/Y/media");
			if (r.status === 200 || r.status === 404) break;
		} catch {
			/* retry */
		}
		await new Promise((r) => setTimeout(r, 100));
	}
	console.log(`[e2e] mock Google Places server up on :5181 (pid ${mock.pid})`);

	console.log("[e2e] applying migrations to " + E2E_PERSIST + "...");
	run("pnpm", [
		"wrangler",
		"d1",
		"migrations",
		"apply",
		"launch-db",
		"--local",
		"--persist-to",
		E2E_PERSIST,
	]);

	console.log("[e2e] wiping user-created rows...");
	wranglerExec(`
		DELETE FROM schedule_votes;
		DELETE FROM schedule_poll_options;
		DELETE FROM schedule_polls;
		DELETE FROM mission_participants;
		DELETE FROM friendships;
		DELETE FROM missions;
		DELETE FROM sites WHERE is_default = 0;
		DELETE FROM users;
	`);

	console.log("[e2e] syncing default sites...");
	run("pnpm", ["sites:sync"]);
}
