#!/usr/bin/env node
/**
 * Prepare .dev.vars for an E2E run.
 *
 * Playwright's webServer is started in parallel with globalSetup, so by
 * the time globalSetup copies .dev.vars.e2e → .dev.vars, `wrangler dev`
 * has usually already booted and read the old (or empty) file. That
 * makes things like MOCK_AUTH=true miss on fresh checkouts / CI.
 *
 * This script is meant to run *before* `playwright test` (from the
 * test:e2e npm script), so webServer sees the right env on first boot.
 */

import { existsSync, copyFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const DEV_VARS = resolve(REPO_ROOT, ".dev.vars");
const DEV_VARS_E2E = resolve(REPO_ROOT, ".dev.vars.e2e");
const DEV_VARS_BACKUP = resolve(REPO_ROOT, ".dev.vars.e2e-backup");

// Safe defaults for a clean checkout. These are not secrets — MOCK_AUTH
// bypasses the GitHub OAuth flow and the Places base URL points at the
// in-process mock server started by global-setup.
const DEFAULT_E2E = `# Auto-generated by scripts/prep-e2e-env.mjs when missing.
# Local overrides are welcome; the file stays gitignored.
MOCK_AUTH=true
GITHUB_CLIENT_SECRET=e2e-unused-mock-auth-is-on
SESSION_SECRET=e2e-session-secret-not-for-production
GOOGLE_MAPS_API_KEY=e2e-mock-key
GOOGLE_PLACES_BASE_URL=http://localhost:5181
`;

if (!existsSync(DEV_VARS_E2E)) {
	console.log("[e2e-prep] .dev.vars.e2e missing — seeding with mock defaults");
	writeFileSync(DEV_VARS_E2E, DEFAULT_E2E);
}
// Preserve a manual .dev.vars (real GOOGLE_MAPS_API_KEY etc.) so the
// teardown script can restore it after the E2E run.
if (existsSync(DEV_VARS) && !existsSync(DEV_VARS_BACKUP)) {
	copyFileSync(DEV_VARS, DEV_VARS_BACKUP);
}
copyFileSync(DEV_VARS_E2E, DEV_VARS);
console.log("[e2e-prep] .dev.vars swapped with .dev.vars.e2e");
